
; load "$NCL_RDEE/lib/rdee.ncl" at the beginning of ncl scripts
; by roadelse @2022-08 in zjlab-11B-303

load "$NCARG_ROOT/lib/ncarg/nclscripts/contrib/cd_inv_string.ncl"
load "$NCARG_ROOT/lib/ncarg/nclscripts/contrib/cd_string.ncl"


load "$NCL_RDEE/lib/_components/rdee_base.ncl"
load "$NCL_RDEE/lib/_components/rdee_array.ncl"
load "$NCL_RDEE/lib/_components/rdee_string.ncl"
load "$NCL_RDEE/lib/_components/rdee_time.ncl"
load "$NCL_RDEE/lib/_components/rdee_geo.ncl"
load "$NCL_RDEE/lib/_components/rdee_io.ncl"
load "$NCL_RDEE/lib/_components/rdee_plot.ncl"
load "$NCL_RDEE/lib/_components/rdee_research.ncl"
